const sortedUnique = (names) => [...new Set(names)].sort();

const renderUnion = (names) => {
  const unique = sortedUnique(names);
  return unique.length === 0 ? 'never' : unique.map((name) => `'${name}'`).join(' | ');
};

/**
 * Collects the hook names a pack's manifest + compiled spec require, keyed the same way as
 * `PackHooks`'s type parameters (`framers`, `parsers`, `keyExtractors`, `streamFramers`,
 * `probes`), each a raw (unsorted, possibly duplicated) name list.
 */
export const hookNames = (manifest, spec) => {
  const chainLinks = (spec.dissect ?? []).flatMap((entry) => entry.chain);
  const messages = (spec.streams ?? []).flatMap((stream) => stream.messages);
  return {
    framers: manifest.containers.map((container) => container.framer),
    parsers: [
      ...chainLinks.flatMap((link) => (link.parser !== undefined ? [link.parser] : [])),
      ...messages.map((message) => message.parser),
    ],
    keyExtractors: (spec.streams ?? []).map((stream) => stream.key),
    streamFramers: (spec.streams ?? []).map((stream) => stream.framer),
    probes: manifest.containers.flatMap((container) =>
      'hook' in container.probe ? [container.probe.hook] : [],
    ),
  };
};

/** Builds the `src/pack.generated.ts` text: hook-name unions plus the runtime `PackDefinition`. */
export const emitGenerated = ({ manifest, spec, specYaml, queries }) => {
  const names = hookNames(manifest, spec);
  const manifestLiteral = JSON.stringify(manifest, null, 2);
  const queriesLiteral = JSON.stringify(queries, null, 2);
  const specYamlLiteral = JSON.stringify(specYaml);
  return `// Generated by byteql-pack build from pack.yaml. Do not edit.
import type { PackDefinition, PackHooks, PackQuery } from '@byteql/core';

export type FramerName = ${renderUnion(names.framers)};
export type ParserName = ${renderUnion(names.parsers)};
export type KeyExtractorName = ${renderUnion(names.keyExtractors)};
export type StreamFramerName = ${renderUnion(names.streamFramers)};
export type ProbeHookName = ${renderUnion(names.probes)};
export type Hooks = PackHooks<FramerName, ParserName, KeyExtractorName, StreamFramerName, ProbeHookName>;

export const definition: PackDefinition = {
  manifest: ${manifestLiteral},
  specYaml: ${specYamlLiteral},
  queries: ${queriesLiteral} satisfies readonly PackQuery[],
};
`;
};
