import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml } from 'yaml';

const packageDirectory = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const source = await readFile(resolve(packageDirectory, 'zip.tables.yaml'), 'utf8');
const generated = `// Generated by scripts/generate-pack.mjs from zip.tables.yaml. Do not edit.\nexport default ${JSON.stringify(source)};\n`;
const querySource = await readFile(resolve(packageDirectory, 'queries.yaml'), 'utf8');
const queryPack = parseYaml(querySource);

if (
  !queryPack ||
  queryPack.version !== '0.1' ||
  queryPack.format !== 'zip' ||
  !Array.isArray(queryPack.queries)
) {
  throw new Error('queries.yaml must declare the ZIP 0.1 query pack');
}

for (const [index, query] of queryPack.queries.entries()) {
  if (
    !query ||
    typeof query.id !== 'string' ||
    typeof query.title !== 'string' ||
    !['grid', 'playback'].includes(query.kind) ||
    typeof query.sql !== 'string'
  ) {
    throw new Error(`queries.yaml query ${index} is invalid`);
  }
}

const generatedQueries = `// Generated by scripts/generate-pack.mjs from queries.yaml. Do not edit.\nimport type { PackQuery } from '@byteql/core';\n\n// prettier-ignore\nconst queries = ${JSON.stringify(queryPack.queries, null, 2)} as const satisfies readonly PackQuery[];\n\nexport default queries;\n`;

await writeFile(resolve(packageDirectory, 'src/zip-tables.generated.ts'), generated);
await writeFile(resolve(packageDirectory, 'src/zip-queries.generated.ts'), generatedQueries);
