// Generated by scripts/generate-pack.mjs from queries.yaml. Do not edit.
import type { PackQuery } from '@byteql/core';

// prettier-ignore
const queries = [
  {
    "id": "overview",
    "title": "Table overview",
    "kind": "grid",
    "sql": "select 'header' as table_name, count(*) as row_count from header\nunion all select 'events', count(*) from events\nunion all select 'tempo', count(*) from tempo\nunion all select 'errors', count(*) from errors\norder by table_name\nlimit 100;\n"
  },
  {
    "id": "play_all",
    "title": "Play all notes",
    "kind": "playback",
    "sql": "with tempo_points as (\n  select tick, us_per_quarter, tempo_id\n  from tempo\n  union all\n  select 0, 500000, 0\n  where not exists (select 1 from tempo where tick = 0)\n), deduped as (\n  select tick, us_per_quarter\n  from tempo_points\n  qualify row_number() over (partition by tick order by tempo_id desc) = 1\n), boundaries as (\n  select tick,\n         us_per_quarter,\n         lag(tick, 1, 0) over (order by tick) as previous_tick,\n         lag(us_per_quarter, 1, 500000) over (order by tick) as previous_tempo\n  from deduped\n), tempo_map as (\n  select tick,\n         us_per_quarter,\n         sum((tick - previous_tick) * previous_tempo / h.division / 1000000.0)\n           over (order by tick rows unbounded preceding) as seconds_at_tick\n  from boundaries\n  cross join header h\n)\nselect tm.seconds_at_tick\n         + (e.tick - tm.tick) * tm.us_per_quarter / h.division / 1000000.0 as seconds,\n       e.note, e.velocity, e.kind, e.channel\nfrom events e\nasof join tempo_map tm on e.tick >= tm.tick\ncross join header h\nwhere e.note is not null\norder by seconds, e.event_id\nlimit 100000;\n"
  },
  {
    "id": "drums",
    "title": "Percussion channel",
    "kind": "playback",
    "sql": "with tempo_points as (\n  select tick, us_per_quarter, tempo_id\n  from tempo\n  union all\n  select 0, 500000, 0\n  where not exists (select 1 from tempo where tick = 0)\n), deduped as (\n  select tick, us_per_quarter\n  from tempo_points\n  qualify row_number() over (partition by tick order by tempo_id desc) = 1\n), boundaries as (\n  select tick,\n         us_per_quarter,\n         lag(tick, 1, 0) over (order by tick) as previous_tick,\n         lag(us_per_quarter, 1, 500000) over (order by tick) as previous_tempo\n  from deduped\n), tempo_map as (\n  select tick,\n         us_per_quarter,\n         sum((tick - previous_tick) * previous_tempo / h.division / 1000000.0)\n           over (order by tick rows unbounded preceding) as seconds_at_tick\n  from boundaries\n  cross join header h\n)\nselect tm.seconds_at_tick\n         + (e.tick - tm.tick) * tm.us_per_quarter / h.division / 1000000.0 as seconds,\n       e.note, e.velocity, e.kind, e.channel\nfrom events e\nasof join tempo_map tm on e.tick >= tm.tick\ncross join header h\nwhere e.note is not null and e.channel = 9\norder by seconds, e.event_id\nlimit 100000;\n"
  },
  {
    "id": "bassline",
    "title": "Low notes",
    "kind": "playback",
    "sql": "with tempo_points as (\n  select tick, us_per_quarter, tempo_id\n  from tempo\n  union all\n  select 0, 500000, 0\n  where not exists (select 1 from tempo where tick = 0)\n), deduped as (\n  select tick, us_per_quarter\n  from tempo_points\n  qualify row_number() over (partition by tick order by tempo_id desc) = 1\n), boundaries as (\n  select tick,\n         us_per_quarter,\n         lag(tick, 1, 0) over (order by tick) as previous_tick,\n         lag(us_per_quarter, 1, 500000) over (order by tick) as previous_tempo\n  from deduped\n), tempo_map as (\n  select tick,\n         us_per_quarter,\n         sum((tick - previous_tick) * previous_tempo / h.division / 1000000.0)\n           over (order by tick rows unbounded preceding) as seconds_at_tick\n  from boundaries\n  cross join header h\n)\nselect tm.seconds_at_tick\n         + (e.tick - tm.tick) * tm.us_per_quarter / h.division / 1000000.0 as seconds,\n       e.note, e.velocity, e.kind, e.channel\nfrom events e\nasof join tempo_map tm on e.tick >= tm.tick\ncross join header h\nwhere e.note is not null and e.note < 48\norder by seconds, e.event_id\nlimit 100000;\n"
  },
  {
    "id": "note_histogram",
    "title": "Note histogram",
    "kind": "grid",
    "sql": "select note, count(*) as event_count\nfrom events\nwhere kind = 'note_on' and note is not null\ngroup by note\norder by event_count desc, note\nlimit 128;\n"
  }
] as const satisfies readonly PackQuery[];

export default queries;
