// Generated by scripts/generate-pack.mjs from queries.yaml. Do not edit.
import type { PackQuery } from '@byteql/core';

// prettier-ignore
const queries = [
  {
    "id": "overview",
    "title": "Table overview",
    "kind": "grid",
    "sql": "select 'local_files' as table_name, count(*) as row_count from local_files\nunion all select 'central_dir_entries', count(*) from central_dir_entries\nunion all select 'end_of_central_dir', count(*) from end_of_central_dir\norder by table_name\nlimit 100;\n"
  },
  {
    "id": "largest_members",
    "title": "Largest members",
    "kind": "grid",
    "sql": "select file_name, compression, uncompressed_size, compressed_size\nfrom central_dir_entries\norder by uncompressed_size desc, file_name\nlimit 100;\n"
  },
  {
    "id": "compression_breakdown",
    "title": "Compression breakdown",
    "kind": "grid",
    "sql": "select compression, count(*) as members,\n       sum(uncompressed_size) as total_uncompressed,\n       sum(compressed_size) as total_compressed\nfrom central_dir_entries\ngroup by compression\norder by members desc\nlimit 100;\n"
  },
  {
    "id": "size_disagreements",
    "title": "Local vs central size mismatches",
    "kind": "grid",
    "sql": "select c.file_name, l.compressed_size as local_size, c.compressed_size as central_size\nfrom central_dir_entries c\njoin local_files l on l.file_name = c.file_name\nwhere l.compressed_size <> c.compressed_size\norder by c.file_name\nlimit 100;\n"
  }
] as const satisfies readonly PackQuery[];

export default queries;
