import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageDirectory = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const source = await readFile(resolve(packageDirectory, 'midi.tables.yaml'), 'utf8');
const generated = `// Generated by scripts/generate-pack.mjs from midi.tables.yaml. Do not edit.\nexport default ${JSON.stringify(source)};\n`;

await writeFile(resolve(packageDirectory, 'src/midi-tables.generated.ts'), generated);
