// Generated by scripts/generate-pack.mjs from queries.yaml. Do not edit.
import type { PackQuery } from '@byteql/core';

// prettier-ignore
const queries = [
  {
    "id": "overview",
    "title": "Table overview",
    "kind": "grid",
    "sql": "select 'packets' as table_name, count(*) as row_count from packets\nunion all select 'ip', count(*) from ip\nunion all select 'tcp', count(*) from tcp\nunion all select 'udp', count(*) from udp\nunion all select 'dns', count(*) from dns\nunion all select 'icmp', count(*) from icmp\nunion all select 'icmpv6', count(*) from icmpv6\nunion all select 'tls', count(*) from tls\norder by table_name\nlimit 100;\n"
  },
  {
    "id": "protocols",
    "title": "Protocol histogram",
    "kind": "grid",
    "sql": "select proto, count(*)\nfrom ip\ngroup by proto\norder by 2 desc\nlimit 100;\n"
  },
  {
    "id": "dns_join",
    "title": "DNS queries by time",
    "kind": "grid",
    "sql": "select p.ts, d.query_name, d.query_type\nfrom dns d\njoin packets p using (packet_id)\norder by p.ts\nlimit 100;\n"
  }
] as const satisfies readonly PackQuery[];

export default queries;
